controller_list:
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
  - name: fake_grip_controller
    type: $(arg fake_execution_type)
    joints:
      - finger_joint1
initial:  # Define initial robot poses per group
  - group: hand
    pose: home